spring:
  application:
    name: cloud-zipkin-service
  main:
    allow-bean-definition-overriding: true

server:
  port: 9411

management:
  metrics:
    web:
      server:
        request:
          autotime:
            enabled: false #Whether to automatically time web server requests